dist: bionic
sudo: required

before_script:
   - sudo apt-get -qq update
   - sudo apt-get install -qq build-essential cmake libfftw3-dev libmbedtls-dev libpcsclite-dev libboost-program-options-dev libconfig++-dev libsctp-dev libczmq-dev libpcsclite-dev rapidjson-dev colordiff ninja-build clang-format-8

language: cpp
        
compiler:
  - gcc
  - clang

script:
 - sudo ln -s /usr/bin/clang-format-diff-8 /usr/bin/clang-format-diff
 - git remote set-branches --add origin master
 - git fetch
 - |
   if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
     # Run only for PRs because target branch is needed to do the clang-format check
     echo "Checking clang-format between TRAVIS_BRANCH=$TRAVIS_BRANCH and TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH"
     ./run-clang-format-diff.sh "$TRAVIS_BRANCH" "$TRAVIS_PULL_REQUEST_BRANCH"
   else
     echo "Skipping clang-format check"
   fi
 - mkdir build
 - cd build
 - cmake -DENABLE_TTCN3=True -DRF_FOUND=True -G Ninja ..
 - ninja
 - ninja test
 - sudo ninja install